{% set name = "flake8-blind-except" %}
{% set version = "0.2.1" %}
{% set sha256 = "f25a575a9dcb3eeb3c760bf9c22db60b8b5a23120224ed1faa9a43f75dd7dd16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pep8

test:
  imports:
    - flake8_blind_except

about:
  home: https://github.com/elijahandrews/flake8-blind-except
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A flake8 extension that checks for blind, catch-all except statements
  description: |
    A flake8 extension that checks for blind, catch-all except statements
  doc_url: https://github.com/elijahandrews/flake8-blind-except
  dev_url: https://github.com/elijahandrews/flake8-blind-except

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - maresb
