# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WDREUVJ7kGNSd4vb03VqNpfREdKpeftR6ghPAi4w8cEb4mNr76Tb7gT3EsumIhwUklwXbtbdUwq0a37AWVzDpFy0GYMURmiVl/m/Jm9UgYjRa3Hl8ZDmn1CDK5XoDTCA4Rr5+kwFeumNHX7qBDaIOVlODfM6Qsb2W26bJgRuf5Oe6vrNcozY/VmnIA+y0VDOm04Zyytm2YWVbpaYWye/1DL+nx3I7FArx/Gt7+CocqYiV4/lICnRxjYiT4/ZGslaGE6sVywG9TacXYXBF2zT0LkiCk834TO3RdPsAsk2KpWkmVIcE+JN+yrAsbLXKrbuNvadeZg8iEbAQCHLnli20YxlgvLznHHPhgqarR8/+/9z/WRM9j/9bzYgMF4IAn5L7wZneRw7YC8P+Rg8xKKqK9bISFloDoM6Bj4LNU7y0XjkjJnxDPRfKNRbd+GJFuV9zeFDG6WgyQV/w0qZxH0k2Tjakmiij35mA2gsrFhZvI95iBlR1X0Psg+uJ/ICAxMq099a9viXsF5uRXXBMKXkvdP2dkcnR6siAzVo53ZvFvTHQcK4NQSuUNwXY94YoR39YRYcNmh/tQZy32pR6watr6cUWF1YmAUBdVspbks5t9h4lG68ZYzbHFFx69pWuCq77iUk8O6Y3AuzwX43UbIELkDO/rVR0+pGAeAtXyZwhTs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
