travis:
  secure:
    BINSTAR_TOKEN: fNeqwn1G3NXRy0z3fxAI7D2alw6fC4Do/wIJuW29syVTLazNpXgK4yBDXB+P16nJfnP4+RYeTvtrvk3HUdE8ToeEBGMnMqF4IQUCNMnRvTeCps+X5TskmE51Poabx3jAeRal7Ot76VDtvojs473FZHDFhm8Kw3sgDj3NAVl6G3ddO3a3uUY7VHiAzbNN48DSMQNTnj3vfbhNZ2XGGMlcmGyxAid9ZbyjTh8+F9pjfA9xdy8IyqMpcFWHerjmU1iGk57/GLP1Cf37yKnpDZ+ct8lMAm1Qksz+DJJzz80aBuXDbU8WuvrOrQCfj5zEpLIX92/E/3P7lrHeHRwu29xiUdDcGI9kx4l48nRwagAKY6QxVyDGClJmaC3DmuXz5TwUMje6mfR4A06jhdWBG5JPGwJsGbAbwoXKzPCLumFpcf9WfX0IBeiJIVZmH0GRpLhP9AJAgEztYDQXPIOwH8vozmpp3g1CY73K4j/YBr4SzW21JLiC0KXBmwL++lhG90Xl4ttFK7OL5TY2q8QCFE0MpGG+y/HZS04LIJIP/oTnoCkl1tDW65LWXc9DxkogEn01c5uGh3ecWxXkL3TybrWbm8RnNScR3wuZjfRmxYkWI19ffNpg+XCuXCnpZ9wlrfkfd+8yfPrwgzbr/LOmUr8OHJ4F6xsYRdSSxcz3cyjDkpM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
