travis:
  secure:
    BINSTAR_TOKEN: WDREUVJ7kGNSd4vb03VqNpfREdKpeftR6ghPAi4w8cEb4mNr76Tb7gT3EsumIhwUklwXbtbdUwq0a37AWVzDpFy0GYMURmiVl/m/Jm9UgYjRa3Hl8ZDmn1CDK5XoDTCA4Rr5+kwFeumNHX7qBDaIOVlODfM6Qsb2W26bJgRuf5Oe6vrNcozY/VmnIA+y0VDOm04Zyytm2YWVbpaYWye/1DL+nx3I7FArx/Gt7+CocqYiV4/lICnRxjYiT4/ZGslaGE6sVywG9TacXYXBF2zT0LkiCk834TO3RdPsAsk2KpWkmVIcE+JN+yrAsbLXKrbuNvadeZg8iEbAQCHLnli20YxlgvLznHHPhgqarR8/+/9z/WRM9j/9bzYgMF4IAn5L7wZneRw7YC8P+Rg8xKKqK9bISFloDoM6Bj4LNU7y0XjkjJnxDPRfKNRbd+GJFuV9zeFDG6WgyQV/w0qZxH0k2Tjakmiij35mA2gsrFhZvI95iBlR1X0Psg+uJ/ICAxMq099a9viXsF5uRXXBMKXkvdP2dkcnR6siAzVo53ZvFvTHQcK4NQSuUNwXY94YoR39YRYcNmh/tQZy32pR6watr6cUWF1YmAUBdVspbks5t9h4lG68ZYzbHFFx69pWuCq77iUk8O6Y3AuzwX43UbIELkDO/rVR0+pGAeAtXyZwhTs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
